### ISSUE TITLE
20230718提示服务器地址无响应

### ISSUE THREAD

**Issue by danshauzi** [CzJam/fastd1ck_enhanced#1]

**Comment by danshauzi** [comment]
023/07/18 09:29:44 关闭fastd1ck_main.sh
2023/07/18 09:29:44 Stop fastd1ck_main process PID: 10781
2023/07/18 09:29:44 fastd1ck_main.sh has stoped.
2023/07/18 09:29:45 --------------------------------------------------------------------------
2023/07/18 09:29:45 迅雷快鸟正在启动...
2023/07/18 09:29:45 绑定IP地址: 192.168.71.22
2023/07/18 09:29:46 模拟机型：meizu MEIZU 20 PRO
2023/07/18 09:29:46 设备标识：wdi10.a0607356b3695b60c9a2c2519e91a1328dd9fb82246b92566aed798500eda694
2023/07/18 09:29:47 帐号登录成功
2023/07/18 09:29:49 迅雷快鸟会员（下行）无效
2023/07/18 09:29:49 迅雷超级会员有效。会员到期时间：2027-06-26
2023/07/18 09:29:49 更新登录时间成功。帐号登录周期：2023-08-17
2023/07/18 09:29:50 获取下行提速入口成功。运营商：上海电信
2023/07/18 09:29:50 下行可以提速。当前带宽 100M，可提升至 500M
2023/07/18 09:29:50 下行带宽提速无效，请稍后再试！

**Comment by danshauzi** [comment]
2023/07/18 09:31:35 _dial_account is sh::ad85590404
2023/07/18 09:31:35 下行可以提速。当前带宽 100M，可提升至 500M
2023/07/18 09:31:35 upgrade 1 is 
{
  "errno": 812,
  "message": "speedup server already speed up",
  "richmessage": "抱歉，服务器请求出错，请重试",
  "sequence": 281607319,
  "timestamp": 1689643896
}
2023/07/18 09:31:35 下行带宽提速无效，请稍后再试！

**Comment by CzJam** [comment]
> 
因为你之前成功登录过，但在没有退出帐号的情况下换了IP，就提示无法加速。你用网页版也一样，提示成功实际上没有加速。
一般等2天就行了。
下次如果要重启路由器，记得先把插件停止了

**Comment by danshauzi** [comment]
> 
OK了，谢谢您
